### ISSUE TITLE
v2.25.1 TimeSeries issues

### ISSUE THREAD

**Issue by PremierShippingPlus** [GoogleCloudPlatform/ops-agent#1095]
We are experiencing issues with ops-agent-opentelemetry-collector
Can you help us with suggestion of reason of this issues please?

1.6759753862789073e+09	error	exporterhelper/queued_retry.go:360	Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors	{"error": "failed to export time series to GCM: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: gce_instance{zone:northamerica-northeast1-a,instance_id:2649997250499570545} timeSeries[0-144]: agent.googleapis.com/processes/disk/write_bytes_count{pid:1976,process:all,command:MsMpEng.exe,owner:NT AUTHORITY\\SYSTEM,command_line:}"}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	C:/Users/ContainerAdministrator/go/pkg/mod/go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/queued_retry.go:360
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
	C:/Users/ContainerAdministrator/go/pkg/mod/go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/metrics.go:136
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	C:/Users/ContainerAdministrator/go/pkg/mod/go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	C:/Users/ContainerAdministrator/go/pkg/mod/go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61

**Comment by braydonk** [comment]
This is a known issue that's been [fixed upstream](https://github.com/shirou/gopsutil/pull/1397). This fix was only [just released in OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.71.0), so we probably can't get it in the next release, but we will likely update to it for the release after. 

In the short-term, the best way to work around this issue is to reboot the server when you start running into this. Since it's based on inaccuracy in the system boot time calculation, rebooting will usually mitigate the issue.

**Comment by PremierShippingPlus** [comment]
Thank you for fast response.
We have tried to reboot the server it doesn't help in our case.

> 

Thank you for fast response.
We have tried to reboot the server it doesn't help in our case.

**Comment by jefferbrecht** [comment]
This is now fixed in [2.27.0](https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.27.0).
