### ISSUE TITLE
High Memory on Windows Server 2019 Core running version 2.29.0

### ISSUE THREAD

**Issue by zdunning13** [GoogleCloudPlatform/ops-agent#1182]
When running the Google Cloud Ops Agent version `2.29.0` or `2.27.0` we are seeing high memory utilization on Windows 2019 Core servers. The memory consumption is coming from `fluent-bit.exe` which is installed with the Ops Agent.

Memory utilization is stable when running on version `2.14.0`.

1. Build custom Windows Server 2019 Core image based on the latest stable Google Cloud provided image. Include Ops Agent 2.27.0 or 2.29.0 in the image with no custom config
3. Create a GCE VM with the custom image & start it
4. Start the Ops Agent at VM startup
5. We see a spike in memory on the VM from `fluent-bit.exe`
6. Restarting the Ops Agent drops memory utilization immediately.

 - VM distro / OS - Windows Server 2019 Core
 - Ops Agent version - 2.27.0 & 2.29.0
 - Ops Agent configuration - no custom config

**Comment by braydonk** [comment]
Hi @zdunning13 thanks for the report. I would recommend opening a support case for this, as going through the customer support channels is the best way we can gather the info we'd need to determine the issue. If you do open a support case, please respond back here with the case number.

**Comment by zdunning13** [comment]
Thanks @braydonk. The Google Case number is `44256464`.

**Comment by braydonk** [comment]
Thanks! This will be a big help for the investigation. I've started working on this, and will update the support case with more information as soon as I have anything to share.

**Comment by 22trevon** [comment]
Created a support case as well with this issue. The GCP engineering team is aware of this. 
For me, this makes my VMs memory max out and no new RDP connections can be established. The VMs have to be rebooted and the ops agent disabled.

**Comment by braydonk** [comment]
Thanks @22trevon, could you please send the case number here? We're getting a bunch of reports so we're gathering them together

**Comment by PhilBrammer** [comment]
Beware, 2.26 has a Windows [time zone](https://github.com/GoogleCloudPlatform/ops-agent/pull/963) [bug](https://github.com/fluent/fluent-bit/pull/6368).

**Comment by braydonk** [comment]
Thanks @PhilBrammer, yes if you have a custom parser with timestamps in your Ops Agent config on Windows then this bug will still be present in Ops Agent versions before the Fluent Bit 2 upgrade. 

The customer case I do have access to mentions that this is with no custom config in the Ops Agent, so if that's the case for anyone else the timezone bug shouldn't affect you.

**Comment by PhilBrammer** [comment]
No.  A standard Ops Agent >= 2.15 and < 2.27 will report Windows event logs in local time (but skewed by GMT).

**Comment by braydonk** [comment]
Right, my mistake. Any VM with a timezone other than UTC was affected by this. So if this applies, downgrading to 2.14 is the best option, which is also what the original comment on this issue suggested they were using previously.

**Comment by PhilBrammer** [comment]
@braydonk and others that can offer help here: The Ops Agent known issues page needs to reflect this Windows time zone bug.  Noting that here in case someone reading can make that change.  New GCP customers pulling down 2.27 (latest) and [being told to pin to 2.26 or older](https://status.cloud.google.com/incidents/pZF1y9HXi6LpyKDuCDf7) is going to cause issues for these customers if they are using Windows servers with non-UTC time zones.

**Comment by jefferbrecht** [comment]
The Windows time zone issue is already documented: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/troubleshoot-run-ingest#event_log_timestamps_are_wrong_on_windows

That issue has existed since the beginning (including 2.16 through 2.26), so the choice at the moment is to either use a newer version with the memory leak or an older version with the time zone issue (with the documented mitigations if needed). Once the fix for the leak is released then affected folks can upgrade to that version to get both fixes.

**Comment by PhilBrammer** [comment]
I'm not sure what you mean by "since the beginning."  2.14 and lower report correctly, and might be worth calling out in that doc.

To be clear, pinning to 2.14 solves both the memory problem and the Windows TZ bug.

**Comment by jefferbrecht** [comment]
No version before 2.27 has ever parsed time zones correctly. The bug has been present in fluent-bit since our initial release, so pinning to 2.14 will not solve the time zone bug.

A separate bug causes Windows Event Logs to not parse the timestamp _at all_ on 2.14, which makes it default to the exporter's default time-of-ingress, which avoids the parsing issue and has the correct time zone -- but the timestamps are wrong anyway since they're not parsed. 

Any custom timestamp parsers using `parse_json` or `parse_regex` that include time zones will not work correctly on 2.14.

**Comment by PhilBrammer** [comment]
This is completely incorrect.  We spin up Windows Server images from GCP (their images; not custom) and deploy 2.14 Ops Agent and do not have a time zone problem.  Going above 2.14 introduces it.

**Comment by PhilBrammer** [comment]
Latency aside (that's the difference between generated and log "timestamp" unless overwritten in the parser), 2.14 logs show up in the correct TZ.
<img width="457" alt="Screenshot 2023-04-13 at 1 52 29 PM" src="https://user-images.githubusercontent.com/25568946/231855743-8bdf087b-4648-406a-9756-a18c9bbfac92.png">

The field, "timestamp" being in UTC (Z) is not a problem. Logging will skew that as per UI settings.  And further, the calculation is correct.

However, above 2.14, the log timestamps appear as local timezone, but in UTC (Z).  So this causes "missing" logs (because when skewed for US time zones, the logs appear in the past).

Example, this log was generated in Windows at 2:50 PM US Central Time (UTC-5).  Note the "receiveTimestamp" is correct, but Stackdriver doesn't use that field.  "Timestamp" is 14:50Z, which should be 19:50Z)

<img width="430" alt="Screenshot 2023-04-13 at 2 51 08 PM" src="https://user-images.githubusercontent.com/25568946/231868628-4252acb6-48a0-4959-8ff1-a70c37f64941.png">

**Comment by PhilBrammer** [comment]
I get what you're saying about mapping event timestamp to log timestamp solves this problem, but as it is now, I'm just trying to help out other customers that can't run the latest ops agent because of the memory issue that they'll likely run into log time zone issues if they are using Windows defaults and are forcing an older ops agent > 2.14.

**Comment by braydonk** [comment]
The memory problem should be resolved in the newly available Ops Agent 2.30 release! :tada: 

Thanks everyone for your patience as I tracked this down. The incident dashboard should reflect the new status soon.

Those interested in technical details can find them in the upstream issues:
https://github.com/fluent/fluent-bit/issues/6748
https://github.com/monkey/monkey/issues/390
