### ISSUE TITLE
build.sh - packages maps and slices missing!

### ISSUE THREAD

**Issue by MaxiCom** [GoogleCloudPlatform/ops-agent#1628]
**Describe the bug**

I just installed go on Ubuntu22.04, then executed the script build.sh from ops-agent repo, i get these errors:

```
confgenerator/confgenerator.go:24:2: package maps is not in GOROOT (/usr/lib/go-1.18/src/maps)
confgenerator/otel/ottl/ottl.go:19:2: package slices is not in GOROOT (/usr/lib/go-1.18/src/slices)
```

**Environment (please complete the following information):**

-Ubuntu22.04
-Clean go environment (as i just installed it for ops-agent)

**Comment by braydonk** [comment]
Hi @MaxiCom:

1. The reason you're getting that error is because the Ops Agent requires Go 1.21, while you have installed Go 1.18. Installing Go 1.21 or 1.22 will fix those issues.
3. That build script will only build the Ops Agent Engine, which contains the configuration generation and health check code. To build a full Ops Agent package that actually contains the subagents, you'll have an easier time using the Dockerfile, see the first step in these docs: https://github.com/GoogleCloudPlatform/ops-agent/blob/master/dev-docs/dev.md#build-and-test-manually-on-gce-vms

Please note that Google does not officially support direct agent builds. If you are just building it to experiment that is fine, but if you are planning to use the agent in production it is strongly recommended to use the official installation method. https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/installation#install-latest-version

**Comment by MaxiCom** [comment]
> Hi @MaxiCom:
> 
> 1. The reason you're getting that error is because the Ops Agent requires Go 1.21 or above, while you have installed Go 1.18. Installing Go 1.21 or 1.22 will fix those issues.
> 3. That build script will only build the Ops Agent Engine, which contains the configuration generation and health check code. To build a full Ops Agent package that actually contains the subagents, you'll have an easier time using the Dockerfile, see the first step in these docs: https://github.com/GoogleCloudPlatform/ops-agent/blob/master/dev-docs/dev.md#build-and-test-manually-on-gce-vms
> 
> Please note that Google does not officially support direct agent builds. If you are just building it to experiment that is fine, but if you are planning to use the agent in production it is strongly recommended to use the official installation method. https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/installation#install-latest-version

Hello @braydonk,

Thank you so much for your answer, i will try to install Go 1.22 as soon as i can and have a look at the docs for the full package. 

Thanks for the links 

Bye. 👋
