### ISSUE TITLE
Systemd service file follows bad practices

### ISSUE THREAD

**Issue by shibumi** [GoogleCloudPlatform/ops-agent#1838]
The Google-Cloud-Ops-Agent systemd service file follows bad systemd service practices.
The file specifies:
```
[Service]
Type=oneshot
# Validate the config.
ExecStartPre=/opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine -in /etc/google-cloud-ops-agent/config.yaml
ExecStart=/bin/true
RemainAfterExit=yes
```

Why this hack with `ExecStart=/bin/true`? Just start the ageny and let systemd monitor it. 

Affected version: 2.52.0-1.el8

**Comment by braydonk** [comment]
The Ops Agent has 3 sub-services, [google-cloud-ops-agent-diagnostics.service](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/systemd/google-cloud-ops-agent-diagnostics.service), [google-cloud-ops-agent-fluent-bit.service](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/systemd/google-cloud-ops-agent-fluent-bit.service), and [google-cloud-ops-agent-opentelemetry-collector.service](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/systemd/google-cloud-ops-agent-opentelemetry-collector.service). This service exists to validate the Ops Agent config, and uses it to generate configuration for the subagents, which are started via `Wants=`.

> Just start the ageny and let systemd monitor it.

It is doing that, but there is no "agent" singular. It is 3 sub services that are started as `Wants=` dependencies, provided the oneshot that validates the Ops Agent config and generates the subagent configs passes.

**Comment by shibumi** [comment]
Strange design decision.

I would have created just three different service file and added for each one of them the config check. For example:
```
ExecStartPre=/opt/google-cloud-ops-agent/libexec/google_cloud_ops_agent_engine -in /etc/google-cloud-ops-agent/config.yaml
ExecStart=@PREFIX@/libexec/google_cloud_ops_agent_diagnostics -config @SYSCONFDIR@/google-cloud-ops-agent/config.yaml
```

This would bring it down to 3 units instead of 4. It would also allow to treat each service independently.

**Comment by braydonk** [comment]
It's not just a config check, it is also config generation. The Ops Agent's `config.yaml` is used to generate config for `opentelemetry-collector` and `fluent-bit`, and the `diagnostics` service reads it to determine the used plugins. If the config generation/validation were done in each service separately, but the Ops Agent config was wrong, you'd have the same failure in all 3 services separately rather than just the `google-cloud-ops-agent` unit.

> It would also allow to treat each service independently.

Most users only want to think of the Ops Agent as one unit, independent of the fact that it's multiple subagents. But for users that do, this capability is not taken away from them. Just because the other units are `PartOf=google-cloud-ops-agent.service` does not mean you can't separately refer to them. You can do `systemctl` commands on any of the individual units the same way. `fluent-bit` and `opentelemetry-collector` depend on each other (`fluent-bit` collects the logs for both agents and `opentelemetry-collector` collects the metrics for both agents) so doing anything like stopping/disabling one and not the other would lead to a broken setup, but nothing is stopping a user from doing that.

**Comment by shibumi** [comment]
I understand. Thank you for the explanation.
