### ISSUE TITLE
Ability to run integration tests quickly

### ISSUE THREAD

**Issue by djaglowski** [GoogleCloudPlatform/ops-agent#198]
Currently, `kokoro` has a monopoly on running integration tests. This presents two major challenges to developers who are adding new integrations to the ops agent.
1. There is a lack of visibility into exactly how `kokoro` sets up and runs the tests. Much can be understood from documentation, the structure of integration test files, and from execution logs. However, there is much that is unclear about the process that would be helpful if made visible. Ideally, `kokoro` would execute a fully self-contained routine that is defined entirely within this repository. This would provide far more insight into issues that arise from incorrect assumptions about the test environment.
2. The development loop is very slow. `kokoro` takes about 15 minutes to run. This causes significant friction and noise, even when working through fairly trivial code changes. Ideally, it would be possible for developers to run a fully self-contained routine locally and in a much shorter period of time. This would allow for faster development cycles and far less churn on pull requests. Aside from providing a mechanism to run locally, much time would be saved if unnecessary recompilations could be skipped, and if developers could target specific integrations and environments (e.g. run `nginx` integration on `debian`.

**Comment by stati0n** [comment]
Question on "locally".  Do you want your local machine to run the system under test as well, as in spin up a local Docker container and install the Ops Agent locally, or would it be acceptable if your local machine was simply orchestrating a GCE instance to do the same but without Kokoro?

**Comment by djaglowski** [comment]
Feel free to disregard the "locally" suggestion if that allows for a better solution. You're probably much better suited to solve this problem than I am, so in general I'd prefer not to impose constraints. My ask is just to enable a much faster development loop. 

For reference, at the OpenTelemetry Collector level, we're able to locally run [integration tests for a specific receiver](https://github.com/observIQ/opentelemetry-components/blob/master/receiver/elasticsearchreceiver/integration_test.go) in just a few seconds total.

**Comment by martijnvans** [comment]
re visibility: we could solve this by open-sourcing the rest of the test code (bash scripts for kokoro, and go). That would be a bit of a project but maybe a week or two's worth of work. Alternatively, we could just copy-paste the existing source code files into github so that people can read them, without hooking them up to actually run. That would be trivial.

re performance: this is borderline impossible to get down to the <1 minute range without a redesign. These tests are end-to-end tests, they need to install "real stuff" (ops agent and applications) onto real VMs and make it upload logs/metrics. Various decisions reflect the desire for realism. In particular:

* Real VMs, instead of containers
* uploading logs/metrics and querying the backend for them, instead of intercepting the upload requests somehow

Both of these take minutes to complete, so we'd have to resolve both of them in order to reduce test runtime that much. At that point it's worth considering a new, faster-running test, possibly in addition to the end-to-end test. But that would be a redesign.

**Comment by djaglowski** [comment]
@martijnvans, Thanks for your thoughts on this. 

Either approach to improving visibility would be very helpful when troubleshooting failures.

Regarding performance: The constraints make sense but I think there must be ways in which we can drastically speed up the _development of integration tests_. We don't necessarily need to run the entire test suite from scratch every time we make a change. We just need a way to run one test case at a time in a way that meaningfully represents how kokoro will run it.

Would it be possible to extract some tooling from kokoro, which would allow a development loop such as the following?

```
spin up a specific environment (e.g. nginx on centos)
loop {
    develop test case for environment
    run test case on environment
}
```

@jsirianni has drafted a script that will will allow us easily to spin up environments [here](https://github.com/observIQ/ops-agent/pull/2#pullrequestreview-764674316). (There may be some meaningful differences from the VMs kokoro uses, but those will become clear if we solve the visibility problem.)

Running the test case is a much more difficult to emulate from the outside though. What do you think? Is there a path forward here that belongs within the ops agent codebase?

**Comment by martijnvans** [comment]
Now that https://github.com/GoogleCloudPlatform/ops-agent/pull/412 has been merged, I think this issue can be closed. Once the requisite setup steps are complete, each test run takes ~15 minutes, depending on platform etc. It's a lot better than it was, and it's honestly as good as we can make it for now without strategies like maintaining a pool of hot VMs ready for use.
