### ISSUE TITLE
Integration tests require Metrics integration, fail with Logs only

### ISSUE THREAD

**Issue by dehaansa** [GoogleCloudPlatform/ops-agent#216]
Discovered in https://github.com/GoogleCloudPlatform/ops-agent/pull/213, the kokoro integration test scripts appear to require metric_name.txt to exist for integration tests for an application to pass.

```
2021/09/23 10:43:53 Attempt 1 of debian-10 test of apache finished with err=error finding metric name for apache: could not read metric_name.txt: open /tmpfs/src/github/unified_agents/integration_test/third_party_apps_data/applications/apache/metric_name.txt: no such file or directory, retryable=false
    third_party_apps_test.go:380: Non-retryable error: error finding metric name for apache: could not read metric_name.txt: open /tmpfs/src/github/unified_agents/integration_test/third_party_apps_data/applications/apache/metric_name.txt: no such file or directory
```

See log here: https://console.cloud.google.com/storage/browser/_details/ops-agents-public-buckets-test-logs/prod/stackdriver_agents/testing/consumer/third_party_apps/presubmit_github/245/20210923-102914/logs/build_and_test.log;tab=live_object?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))

**Comment by martijnvans** [comment]
This is true, we would need a (small) code change to permit a missing/empty metric_name.txt file. As a workaround, you can put something dumb like `agent.googleapis.com/cpu/utilization`, which should always be present, into metric_name.txt for now.

I lean towards allowing an empty file (or maybe a whitespace-only file) and interpreting that as "skip metrics testing". I don't really want to allow a missing file, because it would be too easy to make mistakes where someone thinks that the test ran, but they forgot to include a metrics file and it didn't actually check anything. I know that a missing expected_logs.yaml file means "skip logging tests", which is inconsistent with what I'm saying here, but that's because the logging test feature was developed in a hurry, and I think we should make it so that expected_logs.yaml is required too but is allowed to be empty.

**Comment by jsuereth** [comment]
+1 to consistency between the two and +1 to an explicit empty file going forward.

@martijnvans Thanks for the workaround, @dehaansa let us know if that works for you for now.

**Comment by dehaansa** [comment]
Certainly sounds like a reasonable workaround, will give it a go.

**Comment by Subbarker** [comment]
The code change mentioned is now in, and an empty metric_name.txt file will work.
