### ISSUE TITLE
Ops-agent with custom metrics

### ISSUE THREAD

**Issue by jacek-jablonski** [GoogleCloudPlatform/ops-agent#641]
Hi,
what is the preferred way to send custom metrics with Ops Agent? I would like to send metrics containing dockers' containers memory usage. Previously I did it with collectd. Does Ops Agent allow to replace this use case? If not, is there any preferred way to do this now?
Thanks.

**Comment by rpetti** [comment]
The legacy agent (stackdriver) supported this, but did not support logging. This new Ops Agent supports logging, but doesn't support custom metrics. This is a blocker because it seems you cannot install both stackdriver and ops agent at the same time since ops agent deprecates/replaces stackdriver once installed.

This means we can either have custom metrics (which is needed for MIG autoscaling) or service logging, but not both.

Would greatly appreciate someone from Google chiming in on this apparent loss of functionality and what the new procedure is for getting custom metrics collected using ops agent.

**Comment by franciscovalentecastro** [comment]
There are two feature releases that enable collecting and sending custom metrics with the Ops Agent : 
- Ops Agent release [2.31.0](https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.31.0) - OTLP receiver (Public Preview) - [Public Documentation](https://cloud.google.com/monitoring/agent/ops-agent/otlp)
- Ops Agent release [2.25.0](https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.25.0) - - Prometheus receiver - [Public Documentation](https://cloud.google.com/monitoring/agent/ops-agent/prometheus)
